import java.awt.*;
import java.awt.event.*;
import java.awt.geom.*;
import java.util.*;
import java.util.function.Consumer;
import javax.swing.*;
/** Resolution-independent original artwork with real Swing button hit areas. No game mutation. */
public final class DeskScene extends JPanel {
 private static final long serialVersionUID=1L;
 public enum Item {
  SECURE_PHONE("Secure phone","Pending decisions"), PHONE("Desk phone","Administration contacts"), FOLIO("Signing folio","Legislation"), CABINET("Cabinet book","Appointments and projects"),
  NEWS("Newspapers","Current headlines"), MEMO("Briefing memo","Statistics"), CALENDAR("Calendar","Schedule and month"), LETTERS("Inbox tray","Public correspondence"),
  NOTEBOOK("Promise notebook","Campaign commitments"), OUTBOX("Outbox","Latest activity"), LAPTOP("Laptop","Full dashboard"), SEAL("Office plaque","Career history");
  public final String label,help;Item(String label,String help){this.label=label;this.help=help;}
 }
 public record State(boolean decision,boolean bill,int nominees,int letters,int projects,int completedMonths){public State{if(nominees<0||letters<0||projects<0||completedMonths<0)throw new IllegalArgumentException();}}
 private final State state;private final Map<Item,ObjectButton> buttons=new EnumMap<>(Item.class);private Item selected;
 private boolean pulse,motion=true;private final javax.swing.Timer timer=new javax.swing.Timer(750,e->{pulse=!pulse;repaint();});
 public DeskScene(State state,Consumer<Item> action){this.state=state;setLayout(null);setOpaque(true);setBackground(new Color(31,42,46));setPreferredSize(new Dimension(780,440));for(Item item:Item.values()){ObjectButton b=new ObjectButton(item,()->{selected=item;repaint();action.accept(item);});buttons.put(item,b);add(b);}getAccessibleContext().setAccessibleName("Interactive presidential desk");}
 public void select(Item item){selected=item;repaint();}
 public void motion(boolean enabled){motion=enabled;if(enabled&&state.decision()&&isDisplayable())timer.start();else timer.stop();repaint();}
 @Override public void addNotify(){super.addNotify();if(motion&&state.decision())timer.start();}
 @Override public void removeNotify(){timer.stop();super.removeNotify();}
 @Override public void doLayout(){int gap=8,margin=16,top=40,bottom=36;int w=(getWidth()-2*margin-3*gap)/4,h=(getHeight()-top-bottom-2*gap)/3;int i=0;for(Item item:Item.values()){buttons.get(item).setBounds(margin+(i%4)*(w+gap),top+(i/4)*(h+gap),Math.max(1,w),Math.max(1,h));i++;}}
 @Override protected void paintComponent(Graphics graphics){super.paintComponent(graphics);Graphics2D g=(Graphics2D)graphics.create();g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);int w=getWidth(),h=getHeight();g.setPaint(new GradientPaint(0,0,new Color(83,55,39),w,h,new Color(45,29,24)));g.fillRoundRect(4,22,w-8,h-25,26,26);g.setColor(new Color(189,134,83,24));for(int y=28;y<h;y+=12)g.draw(new QuadCurve2D.Double(12,y,w*.6,y+14,w-12,y-3));g.setColor(new Color(0,0,0,70));g.fillRoundRect(20,42,w-40,h-65,24,24);g.setPaint(new GradientPaint(0,40,new Color(35,67,62),0,h,new Color(21,42,40)));g.fillRoundRect(16,36,w-40,h-65,22,22);g.setColor(new Color(176,149,101));g.drawRoundRect(22,42,w-52,h-77,18,18);g.setFont(new Font(Font.SANS_SERIF,Font.BOLD,12));g.drawString("THE PRESIDENT'S DESK",18,17);g.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,11));g.setColor(new Color(236,222,200));g.drawString("Click an object · Tab / Enter also work",20,h-10);
 // Ambient cup and pen: no hidden game meter, no misleading click target.
 g.setColor(new Color(215,207,185));g.fillOval(w-79,h-27,22,13);g.setColor(new Color(63,36,22));g.fillOval(w-76,h-25,16,8);g.setColor(new Color(217,182,108));g.drawLine(w-48,h-16,w-18,h-22);g.dispose();}
 private int stack(Item item){return switch(item){case FOLIO->state.bill()?3:1;case CABINET->Math.min(4,1+state.nominees());case LETTERS->Math.min(5,1+state.letters());case CALENDAR->Math.min(4,1+state.projects());default->1;};}
 private final class ObjectButton extends JButton {
  private static final long serialVersionUID=1L;private final Item item;
  ObjectButton(Item item,Runnable action){this.item=item;setName("Desk "+item.name());setToolTipText(item.label+" — "+item.help);getAccessibleContext().setAccessibleName(item.label);getAccessibleContext().setAccessibleDescription(item.help);setContentAreaFilled(false);setBorderPainted(false);setFocusPainted(false);setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));addActionListener(e->action.run());addFocusListener(new FocusAdapter(){public void focusGained(FocusEvent e){repaint();}public void focusLost(FocusEvent e){repaint();}});}
  @Override protected void paintComponent(Graphics graphics){Graphics2D g=(Graphics2D)graphics.create();g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);int w=getWidth(),h=getHeight();if(getModel().isRollover()||hasFocus()||selected==item){g.setColor(new Color(244,210,137,45));g.fillRoundRect(0,0,w-1,h-1,12,12);g.setColor(new Color(239,211,151));g.drawRoundRect(1,1,w-3,h-3,12,12);}int labelH=25;double scale=Math.min((w-14)/120.0,(h-labelH-8)/75.0);scale=Math.max(.1,scale);g.translate((w-120*scale)/2,4);g.scale(scale,scale);paintObject(g);g.dispose();g=(Graphics2D)graphics.create();g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,RenderingHints.VALUE_TEXT_ANTIALIAS_ON);g.setFont(new Font(Font.SANS_SERIF,Font.BOLD,Math.max(10,Math.min(13,w/10))));g.setColor(new Color(246,235,210));String label=item.label;int x=Math.max(2,(w-g.getFontMetrics().stringWidth(label))/2);g.drawString(label,x,h-9);g.dispose();}
  private void paintObject(Graphics2D g){g.setColor(new Color(0,0,0,65));g.fillRoundRect(13,13,99,59,9,9);switch(item){
   case SECURE_PHONE,PHONE->{Color body=item==Item.SECURE_PHONE?new Color(163,48,43):new Color(43,53,62);g.setColor(body);g.fillRoundRect(15,24,94,43,16,16);g.setColor(body.brighter());g.setStroke(new BasicStroke(12,BasicStroke.CAP_ROUND,BasicStroke.JOIN_ROUND));g.draw(new QuadCurve2D.Double(23,23,61,-3,102,23));g.setColor(new Color(218,222,209));for(int y=34;y<59;y+=9)for(int x=48;x<74;x+=10)g.fillRoundRect(x,y,6,5,2,2);if(item==Item.SECURE_PHONE&&state.decision()){g.setColor(motion&&pulse?Color.WHITE:new Color(255,184,78));g.fillOval(91,33,9,9);}}
   case LAPTOP->{g.setColor(new Color(155,164,168));g.fillRoundRect(15,3,93,53,5,5);g.setColor(new Color(17,33,47));g.fillRect(20,8,83,42);g.setColor(new Color(94,183,174));g.fillRect(27,16,28,5);g.fillRect(27,27,63,3);g.fillRect(27,36,50,3);g.setColor(new Color(191,195,190));g.fillPolygon(new int[]{15,108,119,5},new int[]{55,55,69,69},4);}
   case SEAL->{g.setColor(new Color(153,106,45));g.fillRoundRect(12,5,98,61,8,8);g.setColor(new Color(221,188,115));g.fillOval(39,10,45,45);g.setColor(new Color(54,73,74));g.fillOval(44,15,35,35);g.setColor(new Color(234,211,153));g.setFont(new Font(Font.SERIF,Font.BOLD,23));g.drawString("★",50,41);g.setFont(new Font(Font.SANS_SERIF,Font.BOLD,8));g.drawString("ADMINISTRATION",27,61);}
   default->{boolean dark=item==Item.FOLIO||item==Item.CABINET||item==Item.NOTEBOOK;for(int i=stack(item)-1;i>=0;i--){g.setColor(new Color(190-i*10,181-i*9,158-i*8));g.fillRoundRect(13+i*2,8+i*3,91,55,3,3);}g.setColor(dark?item==Item.FOLIO?new Color(75,39,32):item==Item.CABINET?new Color(38,62,101):new Color(108,78,41):new Color(234,226,205));g.fillRoundRect(10,4,91,55,3,3);g.setColor(dark?new Color(221,190,129):new Color(57,64,62));g.setFont(new Font(Font.SANS_SERIF,Font.BOLD,9));String word=switch(item){case FOLIO->state.bill()?"BILL ON DESK":"LEGISLATION";case CABINET->"CABINET";case NEWS->"THE DAILY RECORD";case MEMO->"BRIEFING";case CALENDAR->"CALENDAR";case LETTERS->"PUBLIC LETTERS";case NOTEBOOK->"PROMISES";case OUTBOX->"ISSUED / FILED";default->"";};if(item==Item.NEWS)g.setFont(new Font(Font.SANS_SERIF,Font.BOLD,8));g.drawString(word,16,21);g.setStroke(new BasicStroke(1));for(int y=30;y<52;y+=7)g.drawLine(17,y,87-(y%3)*5,y);if(item==Item.LETTERS){g.setColor(new Color(88,97,104));g.fillRect(8,53,104,13);}if(item==Item.CALENDAR){g.setColor(new Color(157,61,48));g.fillRect(10,4,91,8);}}
  }}
 }
}
