import java.util.*;
/** Declarative UI contract. Assets and conditions are identifiers, never gameplay commands. */
public record DeskDefinition(String id,String title,String surface,List<Item> items) {
 public record Position(double x,double y,double width,double height){public Position{if(x<0||y<0||width<=0||height<=0||x+width>1.001||y+height>1.001)throw new IllegalArgumentException("Desk placement out of bounds");}}
 public record Item(String id,String label,String asset,Position position,String target,String menuTheme,String visibility,String notification,String animation,String cosmeticSlot){}
 public DeskDefinition{items=List.copyOf(items);Set<String> ids=new HashSet<>(),targets=new HashSet<>();for(var item:items){if(!ids.add(item.id())||!targets.add(item.target()))throw new IllegalArgumentException("Each desk item needs its own identity and primary target");}}
 private static Item item(int n,String id,String label,String asset,String target,String theme,String notice){return new Item(id,label,(asset.equals("folder")||asset.equals("book")||asset.equals("clipboard"))?asset+":"+id:asset,placement(id),target,theme,"always",notice,"attention-light",id);}
 private static Position placement(String id){return switch(id){case "phone","secure"->new Position(.025,.06,.22,.27);case "map","law"->new Position(.29,.14,.34,.38);case "funds","cabinet"->new Position(.73,.10,.23,.28);case "calendar"->new Position(.69,.61,.27,.30);case "policy"->new Position(.04,.57,.24,.32);case "news"->new Position(.35,.62,.28,.29);case "reports"->new Position(.025,.36,.22,.18);default->new Position(.04,.57,.24,.32);};}
 public static DeskDefinition campaign(){var desk=new DeskDefinition("campaign","CAMPAIGN HEADQUARTERS","campaign",List.of(
 item(0,"phone","Campaign phone","phone","Decisions","phone","decision"),item(1,"map","Campaign map","map","Map","map","none"),item(2,"funds","Fundraising folder","folder","Fundraising","binder","none"),item(3,"calendar","Calendar","calendar","Schedule","calendar","none"),
 item(4,"policy","Policy binder","book","Policy","binder","none"),item(5,"news","Newspaper","news","News","newspaper","news"),item(7,"reports","Campaign reports","clipboard","Statistics","report","activity")) );return new DeskDefinition(desk.id(),desk.title(),desk.surface(),desk.items().stream().map(i->new Item(i.id(),i.label(),i.asset(),switch(i.id()){case "map"->new Position(.29,.035,.46,.44);case "reports"->new Position(.07,.12,.19,.30);case "calendar"->new Position(.77,.07,.19,.29);case "phone"->new Position(.025,.64,.22,.26);case "policy"->new Position(.32,.60,.26,.34);case "funds"->new Position(.65,.62,.23,.20);default->new Position(.71,.84,.23,.15);},i.target(),i.menuTheme(),i.visibility(),i.notification(),i.animation(),i.cosmeticSlot())).toList());}
 public static DeskDefinition presidency(){return new DeskDefinition("presidency","THE OVAL OFFICE","oval",List.of(
 item(0,"secure","Secure phone","phone-red","Decisions","phone","decision"),item(1,"law","Legislation folio","folder","Legislation","binder","bill"),item(2,"cabinet","Cabinet book","book","Cabinet","binder","nominees"),item(3,"calendar","Appointment book","calendar","Schedule","calendar","projects"),
 item(4,"news","Newspaper","news","News","newspaper","news"),item(5,"reports","Office reports","clipboard","Statistics","report","activity")) );}
}
