import java.awt.*;
import java.util.*;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.*;
/** Independent object controls; paints only. Renderer hooks can later load replacement artwork. */
public final class DeskHub extends JPanel {
 private static final long serialVersionUID=1L;
 public interface Assets {void paint(Graphics2D g,String asset,int width,int height,int stack,boolean attention);}
 public record Snapshot(Set<String> visibleConditions,Map<String,Integer> notifications){public Snapshot{visibleConditions=Set.copyOf(visibleConditions);notifications=Map.copyOf(notifications);}public int count(String key){return notifications.getOrDefault(key,0);}}
 private final DeskDefinition definition;private final List<DeskObject> objects=new ArrayList<>();private final Assets assets;
 public DeskHub(DeskDefinition definition,Snapshot snapshot,Consumer<DeskDefinition.Item> open){this(definition,snapshot,open,DeskHub::paintAsset);}
 public DeskHub(DeskDefinition definition,Snapshot snapshot,Consumer<DeskDefinition.Item> open,Assets assets){this.definition=definition;this.assets=assets;setLayout(null);setOpaque(true);setPreferredSize(new Dimension(900,440));for(var item:definition.items())if(item.visibility().equals("always")||snapshot.visibleConditions().contains(item.visibility())){var object=new DeskObject(item,snapshot.count(item.notification()),()->open.accept(item));objects.add(object);add(object);}getAccessibleContext().setAccessibleName(definition.title());}
 @Override public void doLayout(){int top=30,bottom=22;for(var b:objects){var p=b.item.position();b.setBounds((int)(getWidth()*p.x()),top+(int)((getHeight()-top-bottom)*p.y()),(int)(getWidth()*p.width()),(int)((getHeight()-top-bottom)*p.height()));}}
 @Override protected void paintComponent(Graphics graphics){super.paintComponent(graphics);Graphics2D g=(Graphics2D)graphics.create();g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);boolean oval=definition.surface().equals("oval");g.setPaint(new GradientPaint(0,0,new Color(oval?83:110,oval?51:100,oval?34:80),getWidth(),getHeight(),new Color(oval?41:78,oval?28:73,oval?24:62)));g.fillRect(0,0,getWidth(),getHeight());g.setColor(new Color(255,230,185,10));for(int y=30;y<getHeight();y+=22)g.drawLine(0,y,getWidth(),y+6);if(oval){g.setColor(new Color(23,58,51));g.fillRoundRect(14,31,getWidth()-28,getHeight()-53,26,26);g.setColor(new Color(178,148,91));g.drawRoundRect(21,38,getWidth()-42,getHeight()-67,23,23);}else{int ledge=(int)(getHeight()*.57);g.setColor(new Color(167,153,122));g.fillRect(0,0,getWidth(),ledge);g.setColor(new Color(77,62,45));g.fillRect(26,36,getWidth()-52,ledge-48);g.setColor(new Color(130,113,80));g.fillRect(33,43,getWidth()-66,ledge-62);g.setColor(new Color(211,196,155,30));for(int y=48;y<ledge-18;y+=7)g.drawLine(36,y,getWidth()-36,y);g.setColor(new Color(54,40,29));g.fillRect(0,ledge,getWidth(),14);g.setColor(new Color(198,162,109,60));g.drawLine(0,ledge+14,getWidth(),ledge+14);}g.setFont(new Font(Font.SANS_SERIF,Font.BOLD,14));g.setColor(new Color(248,231,197));g.drawString(definition.title(),20,22);g.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,11));g.dispose();}
 private final class DeskObject extends JButton {
  private static final long serialVersionUID=1L;final DeskDefinition.Item item;final int notifications;
  DeskObject(DeskDefinition.Item item,int notifications,Runnable open){this.item=item;this.notifications=notifications;setName("Desk item "+item.id());setToolTipText(item.label()+(notifications>0?" · "+notifications+" updates":""));setContentAreaFilled(false);setBorderPainted(false);DeskStyle.focus(this);setFocusPainted(false);setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));getAccessibleContext().setAccessibleName(item.label()+(notifications>0&&item.notification().equals("decision")?", decision waiting":""));addActionListener(e->open.run());}
  @Override protected void paintComponent(Graphics graphics){Graphics2D g=(Graphics2D)graphics.create();g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);int w=getWidth(),h=getHeight();if(getModel().isRollover()||(hasFocus()&&DeskStyle.keyboardFocus(this))){g.setColor(new Color(255,233,167,40));g.fillRoundRect(0,0,w-1,h-1,10,10);g.setColor(new Color(239,209,144));g.drawRoundRect(1,1,w-3,h-3,10,10);}Graphics2D art=(Graphics2D)g.create();art.translate(7,2);art.rotate(Math.toRadians((item.id().hashCode()%5)-2),(w-14)/2.0,(h-27)/2.0);assets.paint(art,definition.surface().equals("campaign")&&item.position().y()<.5?"wall:"+item.asset():item.asset(),w-14,Math.max(1,h-27),Math.min(4,Math.max(1,notifications)),notifications>0);art.dispose();g.setColor(new Color(250,238,212));g.setFont(new Font(Font.SANS_SERIF,Font.BOLD,Math.min(13,Math.max(10,w/13))));String caption=notifications>0&&item.notification().equals("decision")?"Decision waiting":item.label();if(notifications>0&&item.notification().equals("decision")){g.setColor(DeskStyle.GOLD);g.fillOval(w-26,5,20,20);g.setColor(DeskMenuFrame.INK);g.drawString("!",w-19,20);}g.setColor(new Color(250,238,212));int x=Math.max(2,(w-g.getFontMetrics().stringWidth(caption))/2);g.drawString(caption,x,h-7);g.dispose();}
 }
 static void paintAsset(Graphics2D g,String asset,int width,int height,int stack,boolean attention){boolean wall=asset.startsWith("wall:");if(wall)asset=asset.substring(5);String detail=asset.contains(":")?asset.substring(asset.indexOf(":")+1):"";asset=asset.split(":")[0];double s=Math.min(width/120.0,height/70.0);g.translate((width-120*s)/2,0);g.scale(s,s);g.setColor(new Color(0,0,0,60));g.fillRoundRect(wall?11:12,wall?5:9,91,52,4,4);if(wall)stack=1;
 if(asset.startsWith("phone")){g.setColor(asset.equals("phone-red")?new Color(169,55,47):new Color(49,66,75));g.fillRoundRect(10,22,101,40,13,13);g.setStroke(new BasicStroke(12,BasicStroke.CAP_ROUND,BasicStroke.JOIN_ROUND));g.drawArc(19,5,83,31,5,170);g.setColor(new Color(220,223,211));for(int y=31;y<55;y+=9)for(int x=48;x<77;x+=10)g.fillRect(x,y,5,4);if(attention){g.setColor(new Color(255,196,80));g.fillOval(93,30,9,9);}return;}
 if(asset.equals("seal")){g.setColor(new Color(133,85,39));g.fillRoundRect(10,4,101,59,9,9);g.setColor(new Color(221,191,120));g.fillOval(37,7,49,49);g.setColor(new Color(42,65,65));g.fillOval(42,12,39,39);g.setColor(new Color(237,213,151));g.setFont(new Font(Font.SERIF,Font.BOLD,25));g.drawString("★",48,42);return;}
 for(int i=stack-1;i>=0;i--){g.setColor(new Color(183-i*8,177-i*8,156-i*8));g.fillRect(13+i*2,7+i*3,89,50);}g.setColor(asset.equals("book")||asset.equals("folder")?new Color(66,82,103):new Color(238,230,206));g.fillRoundRect(9,3,91,52,3,3);g.setColor(new Color(93,106,107));if(asset.equals("map")){ElectoralMap.paperOutline(g,12,6,85,47);}else{g.setColor(asset.equals("book")||asset.equals("folder")?new Color(215,192,143):new Color(76,84,78));g.setFont(new Font(Font.SERIF,Font.BOLD,10));g.drawString(asset.equals("news")?"DAILY RECORD":asset.equals("calendar")?"SCHEDULE":switch(detail){case "funds"->"FINANCE";case "policy"->"POLICY";case "debates"->"DEBATE PREP";case "cabinet"->"CABINET";case "law"->"LEGISLATION";case "promises"->"PROMISES";case "history"->"ARCHIVE";case "reports"->"REPORTS";case "activity"->"ACTIVITY";case "actions"->"STAFF MEMO";default->"BRIEFING";},16,20);for(int y=27;y<48;y+=7)g.drawLine(17,y,87,y);}
 if(asset.equals("calendar")){g.setColor(new Color(160,61,47));g.fillRect(9,3,91,8);}if(asset.equals("tray")||asset.equals("letters")){g.setColor(new Color(72,85,91));g.fillRect(7,53,103,12);}if(wall){g.setColor(new Color(75,62,45));g.fillOval(49,5,5,5);g.setColor(new Color(205,174,102));g.fillOval(49,4,4,4);}if(attention){g.setColor(new Color(223,149,62));g.fillOval(90,1,12,12);}
 }
}
