import java.util.*;
/** Additional fictional public-administration stories; not predictions or statutory deadlines. */
public final class WorldStories {
 private WorldStories(){}
 private static WorldEffect e(Object... values){return WorldEffect.of(values);}
 private static WorldEvent.Choice c(String label,int cost,WorldEffect now,int delay,double chance,WorldEffect good,WorldEffect bad,String note){return new WorldEvent.Choice(label,cost,now,delay,chance,good,bad,note);}
 private static WorldEvent s(String id,String title,String text,String flag,WorldEvent.Choice a,WorldEvent.Choice b){return new WorldEvent(id,title,text,3,1,flag,null,0,List.of(a,b));}
 public static List<WorldEvent> added(){return List.of(
 s("wildfire","Wildfire evacuation support","State emergency managers request help moving people from threatened communities. Roads and temporary shelter space are limited.",null,
 c("Coordinate transport and shelter capacity",10,e(WorldMetric.PREPAREDNESS,3,WorldMetric.DEFICIT,.1),2,.85,e(WorldMetric.TRUST,3,WorldMetric.RESILIENCE,2),e(WorldMetric.TRUST,-1),"Existing emergency capacity is used."),
 c("Keep federal support at its current level",0,e(WorldMetric.CAPITAL,2),2,.45,e(),e(WorldMetric.TRUST,-4,WorldMetric.RESILIENCE,-4),"Local capacity may be overwhelmed.")),
 s("water_alert","Drinking-water advisory","A municipal utility reports contamination. Federal technical assistance can help testing, while local officials retain responsibility for the water system.",null,
 c("Send technical support and publish testing updates",8,e(WorldMetric.DEFICIT,.08,WorldMetric.TRUST,1),2,.85,e(WorldMetric.TRUST,3,WorldMetric.RESILIENCE,2),e(WorldMetric.CONFIDENCE,-2),"Testing may reveal wider contamination."),
 c("Wait for the utility's complete report",0,e(WorldMetric.CAPITAL,1),2,.4,e(),e(WorldMetric.TRUST,-4,WorldMetric.CONFIDENCE,-3),"The information gap may persist.")),
 s("rail_spill","Freight derailment near homes","A derailment has disrupted a town. Residents want reliable air and water monitoring before returning home.",null,
 c("Coordinate independent monitoring and clear updates",10,e(WorldMetric.DEFICIT,.1),3,.8,e(WorldMetric.TRUST,4,WorldMetric.RESILIENCE,2),e(WorldMetric.TRUST,-2),"Clean-up and monitoring take time."),
 c("Rely on existing agency updates",0,e(WorldMetric.CAPITAL,2),3,.5,e(WorldMetric.TRUST,1),e(WorldMetric.TRUST,-4,WorldMetric.CONFIDENCE,-2),"Sparse information can undermine confidence.")),
 s("port_backlog","Port cargo backlog","A logistics bottleneck is delaying manufacturers' supplies. Agencies can convene operators but cannot simply order capacity into existence.",null,
 c("Convene operators and resolve administrative delays",8,e(WorldMetric.CAPITAL,-1),3,.7,e(WorldMetric.GROWTH,.15,WorldMetric.INFLATION,-.1),e(WorldMetric.CONFIDENCE,-1),"Private operators must still follow through."),
 c("Let existing commercial arrangements adjust",0,e(WorldMetric.CAPITAL,2),3,.5,e(WorldMetric.GROWTH,.05),e(WorldMetric.INFLATION,.15,WorldMetric.GROWTH,-.1),"Adjustment may be slower.")),
 s("grid_warning","Grid operators warn of a supply gap","An approaching heat wave may strain electricity supply. Operators request coordinated public communication and contingency planning.",null,
 c("Coordinate contingency plans and conservation guidance",10,e(WorldMetric.PREPAREDNESS,3),2,.85,e(WorldMetric.RESILIENCE,3,WorldMetric.TRUST,2),e(WorldMetric.CONFIDENCE,-2),"Coordination reduces but does not remove outage risk."),
 c("Maintain the existing plan",0,e(WorldMetric.CAPITAL,2),2,.45,e(),e(WorldMetric.RESILIENCE,-5,WorldMetric.CONFIDENCE,-4).flag("grid_failure"),"A major outage opens a restoration decision.")),
 s("grid_recovery","Power restoration stalls","The earlier outage has left some communities without dependable power. Utility crews need coordination across service territories.","grid_failure",
 c("Coordinate mutual-aid crews and transparent priorities",10,e(WorldMetric.DEFICIT,.15).clear("grid_failure"),2,.8,e(WorldMetric.RESILIENCE,6,WorldMetric.TRUST,3),e(WorldMetric.TRUST,-1),"Access and equipment remain constraints."),
 c("Leave recovery to the current arrangements",0,e(WorldMetric.CAPITAL,1).clear("grid_failure"),3,.4,e(WorldMetric.RESILIENCE,1),e(WorldMetric.TRUST,-4,WorldMetric.CONFIDENCE,-3),"Uneven restoration may continue.")),
 s("food_recall","Multi-state food recall","Inspectors identify a contaminated product distributed across several states. Consistent public guidance could reduce confusion.",null,
 c("Coordinate traceability and clear recall guidance",7,e(WorldMetric.PREPAREDNESS,2),2,.85,e(WorldMetric.TRUST,2,WorldMetric.CONFIDENCE,1),e(WorldMetric.CONFIDENCE,-1),"The investigation may expand the recall."),
 c("Keep routine recall communications",0,e(WorldMetric.CAPITAL,1),2,.55,e(),e(WorldMetric.TRUST,-2,WorldMetric.CONFIDENCE,-2),"Some affected households may miss the notice.")),
 s("benefits_backlog","Benefits processing backlog","An agency's case backlog is delaying routine payments. Managers propose temporary reassignment with independent quality checks.",null,
 c("Authorize temporary reassignment and quality checks",8,e(WorldMetric.DEFICIT,.08),3,.8,e(WorldMetric.TRUST,3,WorldMetric.INDEPENDENT_APPROVAL,1),e(WorldMetric.TRUST,-1),"Speed must not come at the expense of accuracy."),
 c("Keep staffing on its current assignments",0,e(WorldMetric.CAPITAL,2),3,.45,e(),e(WorldMetric.TRUST,-3,WorldMetric.POPULARITY,-1),"Waiting times may remain high.")),
 s("school_heat","Schools request heat guidance","Local school leaders seek practical heat-safety guidance. Building conditions vary and most operational decisions are local.",null,
 c("Coordinate technical guidance and existing grant support",7,e(WorldMetric.DEFICIT,.05),3,.8,e(WorldMetric.TRUST,2,WorldMetric.PREPAREDNESS,2),e(WorldMetric.TRUST,-1),"Local implementation varies."),
 c("Issue a general statement of concern",0,e(WorldMetric.POPULARITY,.5),3,.4,e(),e(WorldMetric.TRUST,-2),"A statement alone may not improve conditions.")),
 s("insurance_retreat","Insurance availability worsens","Insurers are withdrawing from some high-risk areas. Governors request federal data and mitigation support.",null,
 c("Convene regulators and prioritize risk-reduction support",12,e(WorldMetric.DEFICIT,.1),4,.7,e(WorldMetric.RESILIENCE,4,WorldMetric.CONFIDENCE,2),e(WorldMetric.CONFIDENCE,-2),"Premiums and underwriting remain outside direct control."),
 c("Monitor the market before changing priorities",0,e(WorldMetric.CAPITAL,2),4,.45,e(),e(WorldMetric.CONFIDENCE,-4,WorldMetric.TRUST,-2),"Households may face fewer options.")),
 s("export_dispute","Trading partner contests a rule","A trading partner requests talks about an administrative rule affecting exporters. Both sides face domestic pressure.",null,
 c("Open technical talks while keeping the rule under review",10,e(WorldMetric.UNITY,-1),3,.75,e(WorldMetric.TENSION,-3,WorldMetric.CONFIDENCE,2),e(WorldMetric.TENSION,2),"A negotiated solution is uncertain."),
 c("Defend the current position publicly",0,e(WorldMetric.UNITY,2),3,.45,e(WorldMetric.DONORS,1),e(WorldMetric.TENSION,4,WorldMetric.GROWTH,-.1),"The dispute can weigh on exporters.")),
 s("embassy_evac","Embassy advises assisted departures","Security conditions deteriorate in a fictional partner country. Diplomats recommend helping citizens leave before commercial routes narrow.",null,
 c("Coordinate assisted departures within existing authority",12,e(WorldMetric.DEFICIT,.15),2,.85,e(WorldMetric.TRUST,3,WorldMetric.REPUTATION,2),e(WorldMetric.TENSION,2),"Conditions can change during the operation."),
 c("Rely on commercial departures for now",0,e(WorldMetric.CAPITAL,2),2,.45,e(),e(WorldMetric.TRUST,-4,WorldMetric.TENSION,3),"Later departures may be harder.")),
 s("allied_request","Ally requests a coordinated statement","An ally seeks a joint diplomatic response to pressure from a neighboring government. The proposed wording is contentious.",null,
 c("Negotiate a narrow joint statement",9,e(WorldMetric.CAPITAL,-1),3,.75,e(WorldMetric.TENSION,-3,WorldMetric.REPUTATION,2),e(WorldMetric.TENSION,2),"Consensus limits how forceful the statement can be."),
 c("Issue an independent statement",0,e(WorldMetric.UNITY,1),3,.45,e(WorldMetric.REPUTATION,1),e(WorldMetric.TENSION,3),"Separate messages may reduce coordination.")),
 s("inspector_report","Inspector general flags weak controls","An inspector general reports weaknesses in contract oversight, without making a finding of criminal wrongdoing.",null,
 c("Publish a corrective-action schedule",9,e(WorldMetric.SCANDAL,2),3,.85,e(WorldMetric.TRUST,4,WorldMetric.SCANDAL,-3),e(WorldMetric.SCANDAL,3),"Implementation will be reviewed."),
 c("Seek more internal review before committing",0,e(WorldMetric.CAPITAL,2),3,.4,e(WorldMetric.SCANDAL,-1),e(WorldMetric.TRUST,-3,WorldMetric.SCANDAL,4),"Delay leaves the weaknesses unresolved.")),
 s("records_deadline","Agency records response slips","Staff warn that a records request has outgrown its current processing team. This scenario's response window is a game abstraction, not a legal deadline.",null,
 c("Reassign processing staff and explain the schedule",7,e(WorldMetric.DEFICIT,.04),2,.85,e(WorldMetric.TRUST,2),e(WorldMetric.TRUST,-1),"Other administrative work must wait."),
 c("Keep the current staffing allocation",0,e(WorldMetric.CAPITAL,1),2,.4,e(),e(WorldMetric.TRUST,-3,WorldMetric.SCANDAL,2),"A longer delay can draw oversight scrutiny.")),
 s("agency_vacancy","Senior agency manager announces departure","A senior manager plans to leave. Career staff request a documented handover before the vacancy disrupts work.",null,
 c("Prioritize a lawful handover and continuity plan",8,e(WorldMetric.UNITY,-1),3,.85,e(WorldMetric.TRUST,2,WorldMetric.RESILIENCE,2),e(WorldMetric.CONFIDENCE,-1),"This is continuity planning, not a shortcut around appointment rules."),
 c("Let the existing team handle the transition",0,e(WorldMetric.CAPITAL,2),3,.5,e(),e(WorldMetric.TRUST,-2,WorldMetric.RESILIENCE,-2),"Institutional knowledge may be lost.")),
 s("workforce_strike","Private-sector labor talks stall","A major private-sector negotiation is near a stoppage. Both sides are willing to meet a neutral mediator.",null,
 c("Offer neutral mediation without dictating terms",10,e(WorldMetric.UNITY,-1),3,.7,e(WorldMetric.CONFIDENCE,3,WorldMetric.GROWTH,.1),e(WorldMetric.GROWTH,-.15),"The parties retain control over an agreement."),
 c("Avoid direct involvement",0,e(WorldMetric.CAPITAL,2),3,.45,e(),e(WorldMetric.CONFIDENCE,-3,WorldMetric.GROWTH,-.2),"Negotiations may still succeed without intervention.")),
 s("local_grant","Grant scoring draws complaints","Several local governments question how an authorized grant competition was scored. Review could delay awards.",null,
 c("Publish scoring and commission a process review",9,e(WorldMetric.DEFICIT,.04),3,.85,e(WorldMetric.TRUST,3),e(WorldMetric.TRUST,-1),"Review may require corrections."),
 c("Proceed with the existing award schedule",0,e(WorldMetric.UNITY,1),2,.4,e(WorldMetric.CONFIDENCE,1),e(WorldMetric.SCANDAL,4,WorldMetric.TRUST,-3).flag("grant_review"),"A disputed award may trigger an oversight hearing.")),
 s("grant_hearing","Oversight hearing on grant awards","The earlier grant dispute has reached a legislative oversight committee. Members request documents and witnesses.","grant_review",
 c("Cooperate and correct documented errors",12,e(WorldMetric.UNITY,-1).clear("grant_review"),3,.8,e(WorldMetric.TRUST,3,WorldMetric.SCANDAL,-3),e(WorldMetric.SCANDAL,2),"Cooperation does not predetermine the findings."),
 c("Defend the process using the existing record",0,e(WorldMetric.UNITY,2).clear("grant_review"),3,.35,e(WorldMetric.SCANDAL,-1),e(WorldMetric.TRUST,-4,WorldMetric.SCANDAL,5),"An incomplete record can damage credibility.")),
 s("research_grant","Research pilot reaches a review point","An authorized research pilot has mixed early results. Evaluators request time for independent replication before expansion.",null,
 c("Fund replication within the existing program",8,e(WorldMetric.DEFICIT,.05),4,.7,e(WorldMetric.GROWTH,.08,WorldMetric.TRUST,2),e(WorldMetric.CONFIDENCE,-1),"A null result is possible and should be reported."),
 c("End the pilot and preserve resources",0,e(WorldMetric.DEFICIT,-.03),4,1,e(WorldMetric.CONFIDENCE,-1),e(),"No future pilot benefit is credited.")),
 s("apprenticeships","Employers propose an apprenticeship partnership","Regional employers offer placements if an authorized program can coordinate eligibility and training standards.",null,
 c("Coordinate standards and independent evaluation",9,e(WorldMetric.DEFICIT,.08),4,.75,e(WorldMetric.UNEMPLOYMENT,-.08,WorldMetric.GROWTH,.08),e(WorldMetric.TRUST,-1),"Employer participation may fall short."),
 c("Keep the program at its present scale",0,e(WorldMetric.CAPITAL,2),4,1,e(),e(),"Existing placements continue without expansion.")),
 s("press_pool","Live briefing: an unanswered detail","At a live briefing, a reporter asks why your administration's published explanation omitted an important limitation.",null,
 c("Acknowledge the limitation and clarify it",3,e(WorldMetric.TRUST,1,WorldMetric.POPULARITY,.5),1,.9,e(WorldMetric.TRUST,1),e(WorldMetric.POPULARITY,-.5),"A clear answer can still face criticism."),
 c("Commit to a written answer after checking the facts",0,e(WorldMetric.POPULARITY,-.5),1,.8,e(WorldMetric.TRUST,1),e(WorldMetric.TRUST,-1),"Follow-through matters after the camera moves on.")),
 s("river_flood","Flood forecasts threaten a transport corridor","Emergency managers warn that rising water could close a freight route. Businesses want early, consistent guidance.",null,
 c("Coordinate route planning and local emergency support",10,e(WorldMetric.PREPAREDNESS,3,WorldMetric.DEFICIT,.08),2,.8,e(WorldMetric.RESILIENCE,3),e(WorldMetric.GROWTH,-.1),"Weather can exceed the forecast."),
 c("Wait for observed closures before coordinating",0,e(WorldMetric.CAPITAL,2),2,.45,e(),e(WorldMetric.GROWTH,-.2,WorldMetric.TRUST,-2),"Late rerouting can prolong disruption.")),
 s("data_revision","An economic release is revised","A scheduled statistical revision changes the picture described in your earlier remarks. The statistics office is independent of your messaging team.",null,
 c("Correct the statement and explain the uncertainty",5,e(WorldMetric.TRUST,2,WorldMetric.POPULARITY,-.5),2,.9,e(WorldMetric.REPUTATION,1),e(WorldMetric.POPULARITY,-.5),"Revision is not evidence of manipulation."),
 c("Keep public remarks focused on the next steps",0,e(WorldMetric.CAPITAL,1),2,.5,e(),e(WorldMetric.TRUST,-2),"Avoiding the correction may draw criticism."))
 );}
 public static List<WorldEvent> all(){var result=new ArrayList<>(WorldEventCatalog.all());result.addAll(added());return List.copyOf(result);}
}
