import java.util.List;
/** Source-backed knowledge and rebuttal practice. No scores or model effects. */
public final class DebateFactChecks {
    private DebateFactChecks(){}
    public record Card(String title,String prompt,List<String> choices,String answer,String explanation,String source){public Card{choices=List.copyOf(choices);}}
    private static final String CONSTITUTION="https://www.archives.gov/founding-docs/constitution-transcript";
    private static final String CPI="https://www.bls.gov/cpi/questions-and-answers.htm";
    public static List<Card> all(){var cards=new java.util.ArrayList<Card>(List.of(
        new Card("Rebuttal: a veto claim","Claim: a veto permanently defeats a bill. Which correction is accurate?",List.of("Congress can override through both chambers.","The House alone can override with a two-thirds vote.","Both chambers can override by simple majority."),"Congress can override through both chambers.","Article I, Section 7 provides a two-thirds override in each chamber.",CONSTITUTION),
        new Card("Knowledge: revenue bills","Which statement about revenue bills is accurate?",List.of("They originate in the House; the Senate can amend.","They originate in either chamber; neither can amend.","They originate in the Senate; the House can amend."),"They originate in the House; the Senate can amend.","Article I, Section 7 distinguishes origination from amendment.",CONSTITUTION),
        new Card("Rebuttal: spending authority","Claim: a presidential announcement alone authorizes Treasury spending. What is missing?",List.of("An appropriation made by law.","An executive order without an appropriation.","A committee recommendation without an appropriation."),"An appropriation made by law.","Article I, Section 9 requires lawful appropriations for Treasury withdrawals.",CONSTITUTION),
        new Card("Rebuttal: household experience","Claim: national CPI describes every family's exact inflation experience. Which distinction matters?",List.of("It is an average; household spending patterns differ.","It describes only one family's spending.","It measures every household identically."),"It is an average; household spending patterns differ.","BLS explains that the index does not necessarily match an individual's experience.",CPI),
        new Card("Knowledge: the CPI basket","Which category does BLS exclude from CPI as an investment item?",List.of("Stocks and bonds.","Medical care.","Purchased food."),"Stocks and bonds.","CPI concerns consumer goods and services; investment items are excluded.",CPI),
        new Card("Knowledge: treaty consent","Under Article II, whose consent is required for the President to make a treaty?",List.of("Two-thirds of Senators present.","Two-thirds of both chambers.","A simple majority of the House."),"Two-thirds of Senators present.","Article II, Section 2 assigns treaty consent to the Senate, with two-thirds of Senators present concurring.",CONSTITUTION),
        new Card("Rebuttal: impeachment","Claim: the House's impeachment vote itself removes a president. What is missing?",List.of("A Senate trial and conviction.","A nationwide recall vote.","A second House vote after thirty days."),"A Senate trial and conviction.","The House impeaches; the Senate tries impeachments. Conviction requires two-thirds of members present.",CONSTITUTION),
        new Card("Knowledge: Senate ties","When may the Vice President vote in the Senate?",List.of("When the Senate is equally divided.","On any bill involving the executive branch.","Whenever the majority leader requests it."),"When the Senate is equally divided.","Article I, Section 3 gives the Vice President a vote when the Senate is equally divided.",CONSTITUTION),
        new Card("Rebuttal: slower inflation","Claim: prices must have fallen because a still-positive inflation rate slowed. What distinction is missing?",List.of("Slower price growth is not a falling price level.","Any slowdown means all prices fell.","An index cannot measure changes over time."),"Slower price growth is not a falling price level.","Reading an index: a smaller positive increase remains an increase. CPI tracks average price changes over time.",CPI)
    ));cards.addAll(QuestionBank.politics());cards.addAll(VarietyBank.politics());return List.copyOf(cards);}
    public static List<Card> fun(){var cards=new java.util.ArrayList<Card>(QuestionBank.fun());cards.addAll(VarietyBank.fun());return List.copyOf(cards);}
    public static List<Card> forMode(DebateSettings.Mode mode){return mode==DebateSettings.Mode.FUN?fun():all();}
}
