import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferInt;
import java.util.*;
import javax.swing.*;
public final class PolishTests {
    static int checks;
    static void check(boolean b,String msg){checks++;if(!b)throw new AssertionError(msg);}
    static void paint(ElectoralMap map,BufferedImage image){Graphics2D g=image.createGraphics();map.paint(g);g.dispose();}
    static boolean same(BufferedImage a,BufferedImage b){return Arrays.equals(((DataBufferInt)a.getRaster().getDataBuffer()).getData(),((DataBufferInt)b.getRaster().getDataBuffer()).getData());}
    static void compareReset(ElectoralMap map,BufferedImage image,GameView view){map.dispatchEvent(new MouseEvent(map,MouseEvent.MOUSE_EXITED,0,0,-1,-1,0,false));paint(map,image);ElectoralMap clean=new ElectoralMap(view,"Pennsylvania",s->{});clean.setSize(map.getSize());BufferedImage reference=new BufferedImage(image.getWidth(),image.getHeight(),BufferedImage.TYPE_INT_RGB);paint(clean,reference);check(same(image,reference),"hover/resize returns to exact fresh pixels");}
    public static void main(String[] args)throws Exception{SwingUtilities.invokeAndWait(()->{try{
        DesktopController controller=new DesktopController();controller.start(42,President.Difficulty.NORMAL,President.RunningMate.FUNDRAISER);GameView view=controller.view().campaign();ElectoralMap map=new ElectoralMap(view,"Pennsylvania",s->{});map.setSize(800,460);BufferedImage canvas=new BufferedImage(800,460,BufferedImage.TYPE_INT_RGB);paint(map,canvas);
        for(String state:view.states().stream().map(GameView.StateView::name).toList()){Point point=map.target(state);map.dispatchEvent(new MouseEvent(map,MouseEvent.MOUSE_MOVED,0,0,point.x,point.y,0,false));paint(map,canvas);}compareReset(map,canvas,view);
        map.setSize(700,400);paint(map,canvas);map.setSize(800,460);compareReset(map,canvas,view);
        // Clip repaint must repair old hover strokes just like a full redraw.
        Point point=map.target("Texas");map.dispatchEvent(new MouseEvent(map,MouseEvent.MOUSE_MOVED,0,0,point.x,point.y,0,false));paint(map,canvas);map.dispatchEvent(new MouseEvent(map,MouseEvent.MOUSE_EXITED,0,0,0,0,0,false));for(int x=0;x<800;x+=80){Graphics2D g=canvas.createGraphics();g.setClip(x,0,80,460);map.paint(g);g.dispose();}ElectoralMap fresh=new ElectoralMap(view,"Pennsylvania",s->{});fresh.setSize(800,460);BufferedImage reference=new BufferedImage(800,460,BufferedImage.TYPE_INT_RGB);paint(fresh,reference);check(same(canvas,reference),"clipped repaints repair old hover outlines");
        Set<Integer> first=new HashSet<>();for(var e:DebateSession.catalog()){var order=DebatePresentation.order(42,e.id(),e.options().size());first.add(order.get(0));check(new HashSet<>(order).size()==e.options().size(),"permutation preserves every answer");check(order.equals(DebatePresentation.order(42,e.id(),e.options().size())),"stable on redraw/load");check(e.options().stream().allMatch(o->o.label().length()>60),"answers explain their approach");}check(first.size()==2,"both answer positions occur");
        DesktopPanel panel=new DesktopPanel(controller);int guard=0;while(controller.view().campaign().turnsUsed()<4&&guard++<30){if(!controller.decisionKey().isEmpty())controller.respond(controller.decisionKey(),1);else controller.submit(CareerCommand.campaign(GameCommand.rest()));}controller.respond(controller.decisionKey(),1);var event=controller.view().campaign().pendingEvent();int canonical=0;JButton answer=DesktopTests.find(panel,"Decision option "+canonical);check(answer!=null,"rendered button carries canonical command identity");MapDesktopTests.shot(panel,1024,600,"GUI-DEBATE-READABLE.png");check(answer.getHeight()>=SheetLayout.measure(answer,answer.getWidth()),"long answer has room for wrapped text");String nextKey=controller.decisionKey();answer.doClick();check(!nextKey.equals(controller.decisionKey()),"rotated answer resolves correct round");
        controller.start(8,President.Difficulty.NORMAL,President.RunningMate.FUNDRAISER);controller.submit(CareerCommand.dev(CareerCommand.DeveloperAction.FORCE_WIN));controller.submit(CareerCommand.advance());controller.submit(CareerCommand.advance());DesktopTests.find(panel,"Office").doClick();JButton appoint=DesktopTests.find(panel,"Office NOMINATE 0");check(appoint!=null&&appoint.isEnabled(),"cabinet nomination visible");appoint.doClick();check(controller.view().presidency().cabinet().seats().get(0).official()!=null,"appointment applies through engine");JButton delegate=DesktopTests.find(panel,"Office DELEGATE 0");check(delegate!=null&&delegate.isEnabled(),"delegation visible");delegate.doClick();check(controller.view().presidency().cabinet().seats().get(0).job()!=null,"project scheduled");MapDesktopTests.shot(panel,1024,600,"GUI-OFFICE-CABINET.png");
        controller.submit(CareerCommand.office(OfficeCommand.simple(OfficeCommand.Type.END_MONTH)));DesktopTests.find(panel,"Office").doClick();JTabbedPane tabs=findTabs(panel);tabs.setSelectedIndex(1);JButton reply=DesktopTests.find(panel,"Office REPLY 0");check(reply!=null&&reply.isEnabled(),"public reply visible");reply.doClick();check(controller.view().presidency().correspondence().requests().get(0).answered(),"reply persists");check(!DesktopTests.find(panel,"Office REPLY 0").isEnabled(),"duplicate reply disabled");MapDesktopTests.shot(panel,1024,600,"GUI-OFFICE-REQUESTS.png");
        tabs=findTabs(panel);tabs.setSelectedIndex(2);check(!DesktopTests.find(panel,"Office MIDTERM_TASK 0").isEnabled(),"midterms gated before month 13");
        controller.submit(CareerCommand.dev(CareerCommand.DeveloperAction.MIDTERM_START));DesktopTests.find(panel,"Office").doClick();findTabs(panel).setSelectedIndex(2);JButton visit=DesktopTests.find(panel,"Office MIDTERM_TASK 0");check(visit.isEnabled(),"midterm visit opens");visit.doClick();check(controller.view().presidency().midtermContests().get(0).listened(),"visit persists");
        DesktopTests.find(panel,"Map").doClick();MapDesktopTests.shot(panel,1280,680,"GUI-MAP-RED-BLUE.png");
    }catch(Exception e){throw new RuntimeException(e);}});System.out.println("PolishTests: "+checks+" checks passed");}
    static JTabbedPane findTabs(Container root){for(Component c:root.getComponents()){if(c instanceof JTabbedPane t)return t;if(c instanceof Container child){JTabbedPane found=findTabs(child);if(found!=null)return found;}}return null;}
}
