import java.awt.*;
import java.awt.image.BufferedImage;
import java.nio.file.*;
import java.util.*;
import javax.imageio.ImageIO;
import javax.swing.*;
public class DeskHubTests {
 static void check(boolean b,String why){if(!b)throw new AssertionError(why);}
 static void layout(Container c){c.doLayout();for(Component x:c.getComponents())if(x instanceof Container n)layout(n);}
 static JButton button(Container c,String name){for(Component x:c.getComponents()){if(x instanceof JButton b&&name.equals(b.getName()))return b;if(x instanceof Container n){var found=button(n,name);if(found!=null)return found;}}return null;}
 static void dockCheck(DesktopPanel panel){
  for(Dimension size:java.util.List.of(new Dimension(800,480),new Dimension(1024,650),new Dimension(1366,768))){panel.setSize(size);layout(panel);BorderLayout shell=(BorderLayout)panel.getLayout();check(shell.getLayoutComponent(BorderLayout.NORTH)==null,"no top chrome");Component dock=shell.getLayoutComponent(BorderLayout.SOUTH);Component main=shell.getLayoutComponent(BorderLayout.CENTER);check(dock.getHeight()==112,"fixed compact dock");check(main.getHeight()==size.height-112,"desk fills remaining screen");check(button(panel,"Menu")!=null,"bottom menu always available");check(button(panel,"How to play")==null,"help only in pause menu");}
 }
 static void shot(JComponent c,String name)throws Exception{c.setSize(1024,650);layout(c);var image=new BufferedImage(1024,650,BufferedImage.TYPE_INT_RGB);var g=image.createGraphics();c.printAll(g);g.dispose();ImageIO.write(image,"png",Path.of("docs",name).toFile());}
 public static void main(String[] args)throws Exception{
  check(StatPulse.color(StatPulse.DURATION).equals(StatPulse.BASE),"expired tint returns to base");check(StatPulse.color(StatPulse.DURATION*10).equals(StatPulse.BASE),"rerender cannot replay expired tint");
  CareerEngine pendingCareer=new CareerEngine(91,President.Difficulty.NORMAL,President.RunningMate.FUNDRAISER);for(int i=0;i<12&&pendingCareer.view().campaign().pendingEvent()==null;i++)pendingCareer.submit(CareerCommand.campaign(GameCommand.rest()));check(pendingCareer.view().campaign().pendingEvent()!=null,"pending fixture");check(pendingCareer.submit(CareerCommand.campaign(GameCommand.fundraise())).accepted(),"pending decision permits another action");
SwingUtilities.invokeAndWait(()->{try{
  for(var definition:java.util.List.of(DeskDefinition.campaign(),DeskDefinition.presidency())){var selected=new ArrayList<String>();var desk=new DeskHub(definition,new DeskHub.Snapshot(Set.of(),Map.of("decision",1,"letters",3)),item->selected.add(item.target()));desk.setSize(780,400);layout(desk);var boxes=new ArrayList<Rectangle>();for(Component c:desk.getComponents()){check(c instanceof JButton,"independent button");check(c.isFocusable(),"keyboard focus");check(new Rectangle(0,0,780,400).contains(c.getBounds()),"bounds");for(var box:boxes)check(!box.intersects(c.getBounds()),"hit area overlap");boxes.add(c.getBounds());((JButton)c).doClick();}check(new HashSet<>(selected).size()==definition.items().size(),"unique primary targets");}
  var sample=new GameView.PendingEvent("preview", "Your response", "The moderator has finished the question. Choose a response from your briefing notes.", "", java.util.List.of(new GameView.ChoiceView("Give your answer",true,""),new GameView.ChoiceView("Ask for clarification",true,"")),0,20,"");
  var debate=new DebateWindowPanel(()->sample,()->DebateSettings.DEFAULT,(event,index)->{},()->"20s",()->{},()->{});shot(debate,"debate-theme.png");check(!button(debate,"Decision option 0").isDefaultCapable(),"debate no default action");
  var controller=new DesktopController(()->0L);var panel=new DesktopPanel(controller);shot(panel,"start-screen.png");check(button(panel,"Begin a career")!=null,"start career entry");check(!button(panel,"Begin a career").isDefaultCapable(),"start has no default action");check(button(panel,"Continue from save")!=null,"load entry");controller.start(91,President.Difficulty.NORMAL,President.RunningMate.FUNDRAISER);check(panel.currentPage().equals("Desk"),"campaign desk default");check(((BorderLayout)panel.getLayout()).getLayoutComponent(BorderLayout.WEST)==null,"no persistent sidebar");dockCheck(panel);shot(panel,"campaign-desk.png");button(panel,"Menu").doClick();check(panel.currentPage().equals("Menu")&&controller.paused(),"in-app menu pauses");check(button(panel,"How to play")!=null,"help in pause menu");shot(panel,"pause-menu.png");check(button(panel,"Resume").isShowing()==false,"headless fixture");button(panel,"Resume").doClick();check(panel.currentPage().equals("Desk")&&!controller.paused(),"resume returns to desk");
  for(var item:DeskDefinition.campaign().items()){JButton b=button(panel,"Desk item "+item.id());check(b!=null,"campaign object "+item.id());b.doClick();check(panel.currentPage().equals(item.target()),"campaign destination "+item.target());layout(panel);if(item.target().equals("Schedule"))shot(panel,"calendar-workspace.png");if(item.target().equals("Map"))shot(panel,"paper-map.png");if(item.target().equals("Statistics"))shot(panel,"campaign-reports.png");button(panel,"← Desk").doClick();}
  controller.submit(CareerCommand.dev(CareerCommand.DeveloperAction.FORCE_WIN));controller.submit(CareerCommand.advance());controller.submit(CareerCommand.advance());check(panel.currentPage().equals("Desk"),"inauguration desk");dockCheck(panel);shot(panel,"oval-desk.png");
  for(var item:DeskDefinition.presidency().items()){JButton b=button(panel,"Desk item "+item.id());check(b!=null,"presidential object "+item.id());b.doClick();check(panel.currentPage().equals(item.target()),"presidential destination "+item.target());layout(panel);if(item.target().equals("News"))shot(panel,"newspaper-workspace.png");if(item.target().equals("Legislation"))shot(panel,"binder-workspace.png");button(panel,"← Desk").doClick();}
  panel.getActionMap().get("back").actionPerformed(null);check(panel.currentPage().equals("Menu")&&controller.paused(),"Escape opens pause");panel.getActionMap().get("back").actionPerformed(null);check(panel.currentPage().equals("Desk")&&!controller.paused(),"Escape resumes");
  System.out.println("PASS: both phase hubs, all 13 desk destinations, unique targets, independent keyboard controls, no sidebar, nonoverlapping objects, integrated 1024x650 renders.");
 }catch(Exception e){throw new RuntimeException(e);}});}
}
