import java.awt.*;
import java.nio.file.*;
import java.util.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;

/** Persistent desktop shell. Reads snapshots and submits typed commands only. */
public final class DesktopPanel extends JPanel {
    private static final long serialVersionUID=1L;
    static final Color BG=new Color(15,23,36), CARD=new Color(24,36,52), INK=new Color(232,239,245), MUTED=new Color(155,176,194), ACCENT=new Color(91,216,187);
    final DesktopController controller;
    private final JPanel content=new JPanel(new BorderLayout(16,16)), stats=column(), event=column();
    private final JLabel heading=new JLabel(), timer=new JLabel(), status=new JLabel();
    private String page="Dashboard";
    private final Path saves=Path.of(System.getProperty("user.home"),"PresidentialSimulator","saves");
    public DesktopPanel(DesktopController controller) {
        this.controller=controller;setLayout(new BorderLayout(18,18));setBackground(BG);setBorder(new EmptyBorder(20,20,16,20));
        JPanel top=new JPanel(new BorderLayout());top.setOpaque(false);
        JLabel brand=label("PRESIDENTIAL  /  SIMULATOR",22,INK);top.add(brand,BorderLayout.WEST);heading.setForeground(ACCENT);top.add(heading,BorderLayout.EAST);add(top,BorderLayout.NORTH);
        JPanel nav=column();nav.setPreferredSize(new Dimension(175,100));nav.add(label("COMMAND CENTER",11,MUTED));nav.add(Box.createVerticalStrut(18));
        for(String name:new String[]{"Dashboard","States","Schedule","Policy","Statistics","History"})nav.add(button(name,()->{page=name;render();}));
        nav.add(Box.createVerticalStrut(30));nav.add(button("Latest report",()->dialog(()->{JTextArea report=text(String.join("\n\n",controller.messages));report.setForeground(Color.DARK_GRAY);JScrollPane area=new JScrollPane(report);area.setPreferredSize(new Dimension(650,400));JOptionPane.showMessageDialog(this,area,"Latest report",JOptionPane.INFORMATION_MESSAGE);})));nav.add(button("How to play",this::help));nav.add(button("Save / Load",this::saveMenu));nav.add(button("New career",this::newCareer));nav.add(button("Settings",this::settings));nav.add(button("Developer",this::developer));
        add(nav,BorderLayout.WEST);content.setOpaque(false);add(content,BorderLayout.CENTER);stats.setPreferredSize(new Dimension(235,100));add(stats,BorderLayout.EAST);
        status.setForeground(MUTED);status.setBorder(new EmptyBorder(8,0,0,0));add(status,BorderLayout.SOUTH);
        controller.changed=this::render;controller.timerChanged=this::updateTimer;render();
    }
    static JPanel column(){JPanel p=new JPanel();p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));p.setBackground(CARD);p.setBorder(new EmptyBorder(16,16,16,16));return p;}
    static JLabel label(String s,int size,Color color){JLabel l=new JLabel(s);l.setFont(new Font(Font.SANS_SERIF,Font.BOLD,size));l.setForeground(color);l.setAlignmentX(LEFT_ALIGNMENT);return l;}
    static JTextArea text(String s){JTextArea t=new JTextArea(s);t.setLineWrap(true);t.setWrapStyleWord(true);t.setEditable(false);t.setOpaque(false);t.setForeground(INK);t.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,14));t.setBorder(new EmptyBorder(8,0,12,0));t.setAlignmentX(LEFT_ALIGNMENT);return t;}
    static JButton button(String name,Runnable action){JButton b=new JButton("<html><div style='text-align:center'>"+name.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")+"</div></html>");b.setName(name);b.setAlignmentX(LEFT_ALIGNMENT);b.setMaximumSize(new Dimension(Integer.MAX_VALUE,42));b.setBackground(new Color(39,57,76));b.setForeground(INK);b.setFocusPainted(true);b.setMargin(new Insets(10,12,10,12));b.addActionListener(e->action.run());return b;}
    private void action(JPanel p,String name,CareerCommand cmd){p.add(button(name,()->controller.submit(cmd)));}
    private JScrollPane scroll(JComponent p){JScrollPane s=new JScrollPane(p);s.setBorder(null);s.getViewport().setBackground(CARD);s.getVerticalScrollBar().setUnitIncrement(18);return s;}
    public void render(){
        CareerView v=controller.view();content.removeAll();stats.removeAll();event.removeAll();
        heading.setText(v==null?"DESKTOP PROTOTYPE  •  v0.2":"CAREER YEAR "+v.year()+"  /  "+v.phase().name().replace('_',' ')+(v.developerUsed()?"  /  DEV":""));
        JPanel body=column();body.add(label(page,27,INK));body.add(Box.createVerticalStrut(12));
        if(v==null){body.add(text("Build a campaign. Earn a mandate. Lead the country.\n\nStart a new career to choose your difficulty and running mate, or load an existing save."));body.add(button("Start a new career",this::newCareer));body.add(button("Open a save",this::saveMenu));}
        else switch(page){case "States"->states(body,v);case "Schedule"->schedule(body,v);case "Policy"->policy(body,v);case "Statistics"->statistics(body,v);case "History"->history(body,v);default->dashboard(body,v);}
        content.add(scroll(body),BorderLayout.CENTER);
        if(v!=null){sidebar(v);decision(v);if(event.getComponentCount()>0){JScrollPane s=scroll(event);s.setPreferredSize(new Dimension(500,255));content.add(s,BorderLayout.SOUTH);}}
        else stats.add(text("YOUR FIRST CAMPAIGN\n\n1. Choose a running mate.\n\n2. Complete state objectives.\n\n3. Respond to events and debates.\n\n4. Reach election day."));
        status.setText(controller.busy()?"Working with your save…":"Ready  •  "+(v==null?"Welcome": "Seed "+v.campaign().seed()+"  •  Latest report: "+(controller.messages.isEmpty()?"No updates":controller.messages.get(0))));
        setEnabledTree(content,!controller.busy());updateTimer();revalidate();repaint();
    }
    private static void setEnabledTree(Container p,boolean enabled){if(!enabled)for(Component c:p.getComponents()){c.setEnabled(false);if(c instanceof Container child)setEnabledTree(child,false);}}
    private void dashboard(JPanel p,CareerView v){
        p.add(text(switch(v.phase()){case CAMPAIGN->"Campaign turn "+v.campaign().turnsUsed()+" of "+v.campaign().totalTurns()+". Complete state objectives to build your electoral coalition.";case PRESIDENCY->v.presidency().date()+"  •  "+v.presidency().actionsLeft()+" actions remaining this month";default->"Your career continues. Review the outcome and choose your next step.";}));
        switch(v.phase()){
            case CAMPAIGN->{p.add(button("Choose a state",()->{page="States";render();}));action(p,"Fundraise (+"+v.campaign().fundraisingAmount()+" campaign funds)",CareerCommand.campaign(GameCommand.fundraise()));action(p,"Rest / advance campaign",CareerCommand.campaign(GameCommand.rest()));}
            case ELECTION_REVIEW->{var e=v.elections().get(v.elections().size()-1);p.add(label(e.outcome(),22,ACCENT));p.add(text("Electoral votes: "+e.playerEV()+" / opponent "+e.opponentEV()+"\n"+String.join("\n",e.consequences())));action(p,"Continue",CareerCommand.advance());}
            case TRANSITION->{p.add(text(String.join("\n",v.transitionResources())));action(p,"Begin presidency",CareerCommand.advance());}
            case PRESIDENCY->{
                String[] names=v.governanceOptions().stream().map(a->a.action()+" · "+a.cost()+" office funds").toArray(String[]::new);
                JComboBox<String> options=new JComboBox<>(names);options.setMaximumSize(new Dimension(Integer.MAX_VALUE,36));options.setAlignmentX(LEFT_ALIGNMENT);p.add(options);
                JTextArea explanation=text("");p.add(explanation);
                JButton take=button("Take presidential action",()->controller.submit(CareerCommand.govern(v.governanceOptions().get(options.getSelectedIndex()).action())));p.add(take);
                Runnable select=()->{var a=v.governanceOptions().get(options.getSelectedIndex());explanation.setText(a.available()?WorldSimulation.actionHelp(a.action()):a.reason());take.setEnabled(a.available());};options.addActionListener(e->select.run());select.run();
                p.add(Box.createVerticalStrut(12));action(p,"End month",CareerCommand.office(OfficeCommand.simple(OfficeCommand.Type.END_MONTH)));
            }
            case TERM_REVIEW->{action(p,"Run again",CareerCommand.runAgain());action(p,"Retire",CareerCommand.retire());}
            case OPPOSITION->{p.add(text("Rebuild year "+v.comebackYears()+" of 4. Losses carry forward into future campaigns."));for(var a:CareerCommand.RebuildAction.values())action(p,a.toString(),CareerCommand.rebuild(a));action(p,"Launch comeback campaign",CareerCommand.runAgain());action(p,"Retire",CareerCommand.retire());}
            case RETIRED->{p.add(text("Career complete. Your elections and record remain available in History and Statistics."));p.add(button("Start another career",this::newCareer));}
        }
        p.add(Box.createVerticalStrut(18));p.add(new JSeparator());p.add(label("LATEST REPORT",12,ACCENT));p.add(text(String.join("\n\n",controller.messages)));
    }
    private void states(JPanel p,CareerView v){
        p.add(text("Electoral board · current game projection, not a real-world forecast. Select a state to see objectives, costs and available campaign work."));
        String[] rows=v.campaign().states().stream().map(s->String.format("%-22s %2d EV  ·  %s",s.name(),s.electoralVotes(),s.playerControls()?"Your coalition":"Opponent")).toArray(String[]::new);
        JList<String> list=new JList<>(rows);list.setFont(new Font(Font.MONOSPACED,Font.PLAIN,14));list.setVisibleRowCount(10);list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);JScrollPane pane=scroll(list);pane.setPreferredSize(new Dimension(400,260));p.add(pane);
        JPanel details=column();p.add(details);list.addListSelectionListener(e->{if(e.getValueIsAdjusting()||list.getSelectedIndex()<0)return;details.removeAll();var s=v.campaign().states().get(list.getSelectedIndex());details.add(label(s.name(),20,ACCENT));details.add(text(s.explanation()+"\nObjectives: "+s.objectives()+"\nCompleted: "+s.playerTasks()));for(var a:s.actions()){JButton b=button(a.task()+"  ·  "+a.cost()+" campaign funds",()->controller.submit(CareerCommand.campaign(GameCommand.campaign(s.name(),a.task()))));b.setEnabled(v.phase()==CareerView.Phase.CAMPAIGN&&a.available());b.setToolTipText(a.reason());details.add(b);}details.revalidate();details.repaint();});list.setSelectedIndex(0);
    }
    private void schedule(JPanel p,CareerView v){p.add(text("Campaign time advances through actions. Only live response windows use a real-time countdown."));for(int t:new int[]{4,8,12})p.add(text("DEBATE  /  Turn "+t+"  ·  "+(v.campaign().turnsUsed()>=t?"Reached":"In "+(t-v.campaign().turnsUsed())+" turns")));p.add(text("ELECTION DAY  /  After "+v.campaign().totalTurns()+" campaign turns"));if(v.presidency()!=null)p.add(text("OFFICE  /  "+v.presidency().date()+"\nTerm progress: "+v.termMonths()+" of 48 months\n"+String.join("\n",v.presidency().delayedEffects().stream().map(Object::toString).toList())));for(var s:v.world().scheduled())p.add(text("World month "+s.dueMonth()+"  /  "+s.reason()));}
    private void policy(JPanel p,CareerView v){p.add(text("Campaign pledges carry into office. Propose a bill, secure commitments, complete committee review and floor passage, then sign or veto."));JComboBox<Policy.Issue> issue=new JComboBox<>(Policy.Issue.values());JComboBox<Policy.Approach> approach=new JComboBox<>(Policy.Approach.values());p.add(issue);p.add(approach);p.add(button(v.phase()==CareerView.Phase.CAMPAIGN?"Make campaign pledge":"Propose legislation",()->controller.submit(CareerCommand.office(OfficeCommand.policy(v.phase()==CareerView.Phase.CAMPAIGN?OfficeCommand.Type.PLEDGE:OfficeCommand.Type.PROPOSE,(Policy.Issue)issue.getSelectedItem(),(Policy.Approach)approach.getSelectedItem())))));
        if(v.presidency()!=null){p.add(text("Current bill: "+v.presidency().bill()+"\n"+v.presidency().congress().rule()+"\n"+v.presidency().proceedings()));for(var t:new OfficeCommand.Type[]{OfficeCommand.Type.NEGOTIATE,OfficeCommand.Type.COMMITTEE_REVIEW,OfficeCommand.Type.FLOOR_VOTE,OfficeCommand.Type.SIGN,OfficeCommand.Type.VETO,OfficeCommand.Type.WITHDRAW_BILL})action(p,t.name().replace('_',' '),CareerCommand.office(OfficeCommand.simple(t)));}
        p.add(text("Campaign commitments\n"+String.join("\n",v.campaignPromises().stream().map(Object::toString).toList())));
    }
    private void statistics(JPanel p,CareerView v){p.add(text("Fictional simulation metrics. Office funds are an administrative resource, not the federal budget. Approval measures job performance; popularity is personal favorability."));for(var m:WorldMetric.values())p.add(text(String.format(Locale.ROOT,"%s    %.2f %s",m.label,v.world().get(m),m.unit)));p.add(text("Approval high / low: "+String.format(Locale.ROOT,"%.1f / %.1f",v.world().high(),v.world().low())+"\nMonths served: "+v.servedMonths()+"\nElections won / lost: "+v.electionsWon()+" / "+v.electionsLost()));}
    private void history(JPanel p,CareerView v){for(var e:v.elections())p.add(text(e.year()+"  /  "+e.outcome()+"  /  EV "+e.playerEV()+"–"+e.opponentEV()));var lines=new ArrayList<>(v.history());Collections.reverse(lines);p.add(text(String.join("\n\n",lines)));p.add(text("Campaign record\n"+String.join("\n",v.campaign().history())));}
    private void sidebar(CareerView v){stats.add(label("NATIONAL STATUS",12,ACCENT));if(v.phase()==CareerView.Phase.CAMPAIGN){metric("CAMPAIGN FUNDS",Integer.toString(v.campaign().playerFunds()));metric("ELECTORAL PROJECTION",v.campaign().playerEV()+" / 538");metric("OPPONENT",v.campaign().opponentEV()+" EV");}else{metric("JOB APPROVAL",String.format(Locale.ROOT,"%.1f%%  (%+.1f)",v.world().approval(),v.world().change()));metric("OFFICE FUNDS",Integer.toString(v.treasury()));}
        metric("POPULARITY",String.format(Locale.ROOT,"%.1f",v.world().get(WorldMetric.POPULARITY)));metric("POLITICAL CAPITAL",String.format(Locale.ROOT,"%.0f",v.world().get(WorldMetric.CAPITAL)));metric("ECONOMIC GROWTH",String.format(Locale.ROOT,"%.1f%%",v.world().get(WorldMetric.GROWTH)));if(v.presidency()!=null){metric("YOUR CONGRESS SEATS",v.presidency().congress().houseSeats()+" H / "+v.presidency().congress().senateSeats()+" S");}stats.add(Box.createVerticalStrut(16));stats.add(text("Live clocks pause in dialogs and when this window loses focus."));}
    private void metric(String name,String value){stats.add(Box.createVerticalStrut(18));stats.add(label(name,10,MUTED));stats.add(label(value,24,INK));}
    private void decision(CareerView v){String key=controller.decisionKey();if(key.isEmpty())return;event.add(label("CURRENT DECISION",11,ACCENT));event.add(timer);if(v.phase()==CareerView.Phase.CAMPAIGN){var e=v.campaign().pendingEvent();event.add(label(e.title(),18,INK));event.add(text(e.description()));for(int i=0;i<e.choices().size();i++){int index=i;var c=e.choices().get(i);JButton b=button(c.label(),()->controller.respond(key,index));b.setEnabled(c.available());b.setToolTipText(c.reason());event.add(b);}event.add(text(e.missedResponse()));}else{var e=v.world().pending();event.add(label(e.title(),18,INK));event.add(text(e.description()));for(int i=0;i<e.choices().size();i++){int index=i;var c=e.choices().get(i);JButton b=button(c.label()+"  ·  "+c.capitalCost()+" capital",()->controller.respond(key,index));b.setEnabled(v.world().get(WorldMetric.CAPITAL)>=c.capitalCost());b.setToolTipText(c.consequence());event.add(b);}event.add(text(v.world().missedResponse()));}}
    void updateTimer(){timer.setForeground(ACCENT);timer.setText(controller.seconds()>0?(!controller.realtime()?"CLOCK DISABLED  ·  ":controller.paused()?"PAUSED  ·  ":"RESPOND IN  ")+controller.seconds()+"s":turnDeadline());}
    private String turnDeadline(){var v=controller.view();if(v==null)return "";if(v.phase()==CareerView.Phase.CAMPAIGN&&v.campaign().pendingEvent()!=null)return "DEADLINE  ·  Campaign turn "+v.campaign().pendingEvent().dueTurn();return "DEADLINE  ·  World month "+v.world().dueMonth();}
    private void dialog(Runnable task){controller.pause();try{task.run();}finally{controller.resume();}}
    private void help(){dialog(()->JOptionPane.showMessageDialog(this,"CAMPAIGN\nVisit States and complete the listed objectives. Every campaign action uses a turn.\nFundraising restores funds. Your opponent also acts. Debates occur on turns 4, 8 and 12.\n\nDECISIONS\nRead the current event and click a response. Live appearances have countdowns;\nother deadlines advance with game turns. Ignoring an event has consequences.\n\nPRESIDENCY\nChoose up to two actions each month, then End month. Use Policy for legislation.\nApproval, the economy and your record carry forward into future campaigns.\n\nSAVES\nSave / Load offers three manual slots and a quicksave. Phase changes autosave.\nSave before exiting to preserve actions since the last transition.\nDialogs and switching away from this window pause live clocks.\n\nStatistics shows the full metrics; History preserves your career record.","How to play",JOptionPane.INFORMATION_MESSAGE));}
    private void newCareer(){if(controller.busy())return;dialog(()->{if(controller.view()!=null&&JOptionPane.showConfirmDialog(this,"Start over? Save your current career first if you want to keep it.","New career",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return;JComboBox<President.Difficulty>d=new JComboBox<>(President.Difficulty.values());JComboBox<President.RunningMate>m=new JComboBox<>(President.RunningMate.values());JTextField seed=new JTextField(Long.toString(System.currentTimeMillis()));Object[] fields={"Difficulty",d,"Running mate",m,"Random seed (any whole number)",seed};if(JOptionPane.showConfirmDialog(this,fields,"New career",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)try{page="Dashboard";controller.start(Long.parseLong(seed.getText().strip()),(President.Difficulty)d.getSelectedItem(),(President.RunningMate)m.getSelectedItem());}catch(NumberFormatException e){JOptionPane.showMessageDialog(this,"Please enter a whole-number seed.");}});}
    private void saveMenu(){if(controller.busy())return;dialog(()->{String[] choices={"Load autosave","Save slot 1","Save slot 2","Save slot 3","Load slot 1","Load slot 2","Load slot 3","Quicksave","Load quicksave","Open save file"};Object selected=JOptionPane.showInputDialog(this,"Choose a save action. Loading replaces the current unsaved career.","Save / Load",JOptionPane.PLAIN_MESSAGE,null,choices,choices[0]);if(selected==null)return;String s=selected.toString();if(s.equals("Open save file")){JFileChooser f=new JFileChooser(saves.toFile());if(f.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)controller.load(f.getSelectedFile().toPath());return;}Path path=saves.resolve(s.equals("Load autosave")?"autosave.properties":s.toLowerCase().contains("quicksave")?"quicksave.properties":"slot-"+s.charAt(s.length()-1)+".properties");if(s.startsWith("Load")){if(JOptionPane.showConfirmDialog(this,"Replace the current career with this save?","Load",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)controller.load(path);}else if(controller.view()!=null){if(!Files.exists(path)||JOptionPane.showConfirmDialog(this,"Replace this slot? Previous versions are kept as backups.","Save",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)controller.save(path,()->{});}});}
    private void settings(){if(controller.view()==null)return;dialog(()->{int x=JOptionPane.showOptionDialog(this,"Live response countdowns","Settings",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,new String[]{"Enable","Disable","Cancel"},"Enable");if(x==0||x==1)controller.submit(CareerCommand.office(OfficeCommand.choice(OfficeCommand.Type.REALTIME_MODE,x==0?1:0)));});}
    private void developer(){if(controller.view()==null)return;dialog(()->{Object x=JOptionPane.showInputDialog(this,"Developer actions mark this career as modified.","Developer tools",JOptionPane.WARNING_MESSAGE,null,CareerCommand.DeveloperAction.values(),CareerCommand.DeveloperAction.FORCE_WIN);if(x!=null)controller.submit(CareerCommand.dev((CareerCommand.DeveloperAction)x));});}
    public void requestClose(Runnable close){if(controller.busy())return;if(controller.view()==null){close.run();return;}dialog(()->{int x=JOptionPane.showOptionDialog(this,"Save before leaving?","Exit",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,new String[]{"Save and exit","Exit without saving","Cancel"},"Save and exit");if(x==0)controller.save(saves.resolve("quicksave.properties"),close);else if(x==1)close.run();});}
}
