import java.awt.*;
import javax.swing.*;

/** GUI for existing appointment, correspondence and midterm commands. */
public final class OfficeWorkspace extends JPanel {
    private static final long serialVersionUID=1L;
    public static final class Selection {int tab,department,request,contest;}
    private final DesktopController controller;
    private final CareerView career;
    private final Presidency.View office;
    public OfficeWorkspace(DesktopController controller,Selection selection){
        this.controller=controller;career=controller.view();office=career.presidency();setLayout(new BorderLayout(8,8));setBackground(DesktopPanel.CARD);setBorder(new javax.swing.border.EmptyBorder(8,8,8,8));
        if(career.phase()!=CareerView.Phase.PRESIDENCY){add(DesktopPanel.text("Your Office opens after inauguration. You can continue your campaign from Dashboard."));return;}
        JPanel header=DesktopPanel.column();header.add(DesktopPanel.label("Presidential office",22,DesktopPanel.INK));header.add(DesktopPanel.text(office.date()+" · "+office.actionsLeft()+" actions available · Appointments, replies and visits each use one action."));
        header.add(DesktopPanel.button("End month",()->controller.submit(CareerCommand.office(OfficeCommand.simple(OfficeCommand.Type.END_MONTH)))));add(header,BorderLayout.NORTH);
        JTabbedPane tabs=new JTabbedPane();tabs.setBackground(DesktopPanel.CARD);tabs.setForeground(DesktopPanel.INK);tabs.addTab("Cabinet",cabinet(selection));tabs.addTab("Public requests",requests(selection));tabs.addTab("Midterms",midterms(selection));tabs.setSelectedIndex(selection.tab);tabs.addChangeListener(e->selection.tab=tabs.getSelectedIndex());add(tabs,BorderLayout.CENTER);
    }
    private JScrollPane scroll(JPanel p){JScrollPane s=new JScrollPane(p);s.setBorder(null);s.getVerticalScrollBar().setUnitIncrement(18);return s;}
    private void command(JPanel p,String label,OfficeCommand.Type type,int choice,String problem){
        if(problem.isEmpty()&&office.actionsLeft()==0)problem="No actions left. End the month to continue.";
        if(problem.isEmpty()&&controller.busy())problem="Please wait for the save or load to finish.";
        JButton b=DesktopPanel.button(label,()->controller.submit(CareerCommand.office(OfficeCommand.choice(type,choice))));b.setName("Office "+type+" "+choice);b.setEnabled(problem.isEmpty());p.add(b);
        if(!problem.isEmpty()){b.setToolTipText(problem);p.add(DesktopPanel.text(problem));}
    }
    private JComponent cabinet(Selection selection){
        JPanel p=DesktopPanel.column();String[] names=java.util.Arrays.stream(Cabinet.Department.values()).map(d->Cabinet.departmentLabel(d,career.rules())).toArray(String[]::new);JComboBox<String> choose=new JComboBox<>(names);choose.setSelectedIndex(selection.department);choose.setAlignmentX(LEFT_ALIGNMENT);choose.setMaximumSize(new Dimension(Integer.MAX_VALUE,32));p.add(choose);JPanel detail=DesktopPanel.column();p.add(detail);
        Runnable update=()->{selection.department=choose.getSelectedIndex();int d=selection.department;var seat=office.cabinet().seats().get(d);detail.removeAll();
            detail.add(DesktopPanel.text(seat.official()!=null?"Serving: "+seat.official().name():seat.nominee()!=null?"Nominee: "+seat.nominee().name()+" · Hearing after month "+seat.hearingMonth():"Vacant. Choose a candidate to begin."));
            if(seat.official()==null&&seat.nominee()==null){for(var c:Cabinet.candidates())if(c.department()==seat.department()){detail.add(DesktopPanel.text(c.name()+"\n"+c.background()+"\nDelegated project: "+c.projectCost()+" office funds; "+c.deliveryMonths()+" months."));command(detail,d==0?"Appoint "+c.name():"Nominate "+c.name(),OfficeCommand.Type.NOMINATE,c.id(),"");}}
            else if(seat.nominee()!=null){String issue=office.monthsCompleted()<seat.hearingMonth()?"Hearing not finished. Advance to the next month.":office.congress().senateSeats()<50&&!seat.nominee().consensus()&&!seat.agreement()?"Secure confirmation support first.":"";command(detail,"Confirm nominee",OfficeCommand.Type.CONFIRM,d,issue);command(detail,"Secure confirmation support",OfficeCommand.Type.NOMINEE_SUPPORT,d,seat.agreement()?"Support is already secured.":"");}
            else{detail.add(DesktopPanel.text("Annual assignment: "+Cabinet.project(seat.department())+(seat.job()==null?"":"\nIn progress: due after month "+seat.job().dueMonth())));String issue=seat.job()!=null?"An assignment is already underway.":seat.lastAssignedYear()==office.monthsCompleted()/12?"This department has completed its annual assignment.":office.treasury()<seat.official().projectCost()?"Not enough office funds for this project.":"";command(detail,"Delegate project · "+seat.official().projectCost()+" office funds",OfficeCommand.Type.DELEGATE,d,issue);}
            if(seat.official()!=null||seat.nominee()!=null){JButton remove=DesktopPanel.button(seat.official()!=null?"Dismiss official…":"Withdraw nomination…",()->{controller.pause();try{if(JOptionPane.showConfirmDialog(this,"Remove this appointment? Any active assignment is cancelled without a refund.","Confirm removal",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)controller.submit(CareerCommand.office(OfficeCommand.choice(OfficeCommand.Type.DISMISS,d)));}finally{controller.resume();}});remove.setEnabled(office.actionsLeft()>0&&!controller.busy());detail.add(remove);}detail.revalidate();detail.repaint();};choose.addActionListener(e->update.run());update.run();return scroll(p);
    }
    private JComponent requests(Selection selection){
        JPanel p=DesktopPanel.column();p.add(DesktopPanel.text("A reply acknowledges a concern. Enacting and delivering the requested initiative fulfills it. Use Policy to take the request further."));JComboBox<String> choose=new JComboBox<>(office.correspondence().requests().stream().map(r->r.group()+" — "+DesktopPanel.friendlyName(r.status())).toArray(String[]::new));choose.setSelectedIndex(selection.request);choose.setAlignmentX(LEFT_ALIGNMENT);choose.setMaximumSize(new Dimension(Integer.MAX_VALUE,32));p.add(choose);JPanel detail=DesktopPanel.column();p.add(detail);Runnable update=()->{selection.request=choose.getSelectedIndex();var r=office.correspondence().requests().get(selection.request);detail.removeAll();detail.add(DesktopPanel.text(r.group()+"\nRequest: "+r.request()+"\nStatus: "+DesktopPanel.friendlyName(r.status())));command(detail,"Publish an acknowledgment · 1 action",OfficeCommand.Type.REPLY,r.id(),r.answered()?"You have already replied. The request's delivery status remains visible.":"");detail.revalidate();detail.repaint();};choose.addActionListener(e->update.run());update.run();return scroll(p);
    }
    private JComponent midterms(Selection selection){
        JPanel p=DesktopPanel.column();p.add(DesktopPanel.text("Support allies with listening and organizing visits. This is the existing simplified contest board. Campaigning opens in month 13 and closes at the term's midterm election."));JComboBox<String> choose=new JComboBox<>(office.midtermContests().stream().map(MidtermCampaign.Contest::name).toArray(String[]::new));choose.setSelectedIndex(selection.contest);choose.setAlignmentX(LEFT_ALIGNMENT);choose.setMaximumSize(new Dimension(Integer.MAX_VALUE,32));p.add(choose);JPanel detail=DesktopPanel.column();p.add(detail);Runnable update=()->{selection.contest=choose.getSelectedIndex();var c=office.midtermContests().get(selection.contest);detail.removeAll();detail.add(DesktopPanel.text(c.name()+"\nListening visit: "+(c.listened()?"Completed":"Not completed")+"\nOrganizing visit: "+(c.organized()?"Completed":"Not completed")+"\nResult: "+c.outcome()));String issue=office.monthsCompleted()<12?"Opens at the start of month 13.":office.monthsCompleted()>=career.rules().midtermElectionMonth()?"Midterm campaigning has closed.":"";command(detail,"Listening visit · 1 action",OfficeCommand.Type.MIDTERM_TASK,c.id()*2,!issue.isEmpty()?issue:c.listened()?"Already completed.":"");command(detail,"Organizing visit · 1 action",OfficeCommand.Type.MIDTERM_TASK,c.id()*2+1,!issue.isEmpty()?issue:c.organized()?"Already completed.":"");detail.revalidate();detail.repaint();};choose.addActionListener(e->update.run());update.run();return scroll(p);
    }
}
